### PR TITLE
Dart Null Safety

### PR DESCRIPTION
**Pull request by daninow**
I made some changes to adopt null safety. Check and if you want add this to your great project.

### CODE REVIEW

**Comment by apinprastya** [comment]
I think we need a flag for backward compatibility, some people maybe still working without null safety. Could you please add 2 version of generators? null safety and without null safety?
I will help with the UI side.

**Comment by daninow** [comment]
Well, same it's happening with Dart Data Class Generator extension, and their solution is to upgrade, and if any wants to use backward compatibility it's easy in vscode to change to an older version.

Captura de pantalla 2021-04-03 a las 14 44 23

**Comment by apinprastya** [comment]
I am OK with it, null safety is the future. Could you please add something on the readme? like stating that starting version 0.2.0 is using nullsafety and for non null safety install the 0.1.7 version.
And also add new entry on the changelog, credit your name there like:

> 0.2.0
> - null safety generated code (your credit)

When it is done, I will release version 0.2.0

**Comment by daninow** [comment]
Yes, of course, i will include these changes. Thank you.

**Pull request merged**
